on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE:STRING=Release
          cmake --build ./build --config Release --target strip
      - name: Delete previous release/tag
        if: github.ref == 'refs/heads/main'
        run: gh release delete latest --cleanup-tag || git push --delete origin latest
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release the new binary
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "latest"
          prerelease: true
          name: "Latest commit that compiles"
          body: |
            This automatic prerelease is built from commit ${{ github.sha }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ github.event.head_commit.message }}
          files: build/strip
